using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;

namespace CodeGenerator
{
    [Generator]
    public class ServerHandlerGenerator : IIncrementalGenerator
    {
        private const string InstallerSuffix = "Installer";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: GeneratorFilterHelper.IsClassWithAttribute,
                    transform: (ctx, _) => GeneratorFilterHelper.GetClassWithAttribute(ctx, "ServerHandler"))
                .Where(m => m != null && !m.IsAbstract);

            context.RegisterSourceOutput(classDeclarations, (spc, symbol) => Execute(spc, symbol));
        }

        private static void Execute(SourceProductionContext context, INamedTypeSymbol symbol)
        {
            try
            {
                var namespaceName = symbol.ContainingNamespace.ToDisplayString();
                var handlerType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var installerName = symbol.Name + InstallerSuffix;

                var sourceBuilder = new StringBuilder();
                sourceBuilder.AppendLine("// <auto-generated/>");
                sourceBuilder.AppendLine("using UnityEngine;");
                sourceBuilder.AppendLine($"namespace {namespaceName}");
                sourceBuilder.AppendLine("{");
                sourceBuilder.AppendLine($"    public static class {installerName}");
                sourceBuilder.AppendLine("    {");
                sourceBuilder.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
                sourceBuilder.AppendLine("        private static void Install()");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine($"            global::O2un.Core.Network.ServerPacketHandlers.AddInstaller(static registry => registry.Register(new {handlerType}()));");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine("    }");
                sourceBuilder.AppendLine("}");

                context.AddSource($"{installerName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
            }
            catch (Exception ex)
            {
                GeneratorLogHelper.LogError(context, nameof(ServerHandlerGenerator), ex);
            }
        }
    }
}
