using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using O2un.Core.Utils;
using UnityEditor;
using UnityEditor.Localization;

namespace O2un.Core.Localization.Editor
{
    /// <summary>
    /// String Table Collection 이름에서 <c>LocalTable</c> enum 을 뽑는다.
    ///
    /// Roslyn 소스 제너레이터로는 못 만든다 — 테이블은 컴파일에 들어가지 않는 에셋이라
    /// 컴파일러가 볼 수 없다. 그래서 Editor 쪽에서 파일을 직접 쓴다.
    /// </summary>
    public static class LocalTableGenerator
    {
        private const string OUTPUT_PATH = "Assets/0_Framework/00_Script/Core/Localization/Generated/LocalTable.g.cs";
        private const string NONE_MEMBER = "None";

        [MenuItem("O2un/Localization/Rebuild LocalTable")]
        public static void Rebuild()
        {
            if (false == TryWrite())
            {
                Log.Print(Log.LogLevel.Info, "LocalTable 은 이미 테이블 목록과 같다.");
            }
        }

        /// <summary>내용이 달라졌을 때만 쓴다. 같은 파일을 다시 쓰면 도메인 리로드만 도는 탓이다.</summary>
        public static bool TryWrite()
        {
            string generated = Build(CollectTableNames());

            if (true == File.Exists(OUTPUT_PATH) && File.ReadAllText(OUTPUT_PATH) == generated)
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(OUTPUT_PATH));
            File.WriteAllText(OUTPUT_PATH, generated);
            AssetDatabase.ImportAsset(OUTPUT_PATH);

            Log.Print(Log.LogLevel.Info, $"LocalTable 을 다시 생성했다. ({OUTPUT_PATH})");

            return true;
        }

        private static List<string> CollectTableNames()
        {
            List<string> names = new();

            foreach (StringTableCollection collection in LocalizationEditorSettings.GetStringTableCollections())
            {
                if (null == collection)
                {
                    continue;
                }

                if (true == string.IsNullOrWhiteSpace(collection.TableCollectionName))
                {
                    continue;
                }

                names.Add(collection.TableCollectionName);
            }

            names.Sort(StringComparer.Ordinal);

            return names;
        }

        private static string Build(List<string> tableNames)
        {
            StringBuilder builder = new();

            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     O2un/Localization/Rebuild LocalTable 메뉴가 String Table Collection 에서 생성한다.");
            builder.AppendLine("//     직접 고치면 다음 생성에서 덮어써진다.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine();
            builder.AppendLine("namespace O2un.Core.Localization");
            builder.AppendLine("{");
            builder.AppendLine("    public enum LocalTable");
            builder.AppendLine("    {");
            builder.AppendLine($"        {NONE_MEMBER} = 0,");

            List<string> members = ToUniqueMembers(tableNames);

            for (int i = 0; i < members.Count; ++i)
            {
                builder.AppendLine($"        {members[i]} = {i + 1},");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public static class LocalTableExtensions");
            builder.AppendLine("    {");
            builder.AppendLine("        public static string ToTableName(this LocalTable table)");
            builder.AppendLine("        {");
            builder.AppendLine("            return table switch");
            builder.AppendLine("            {");

            for (int i = 0; i < members.Count; ++i)
            {
                builder.AppendLine($"                LocalTable.{members[i]} => \"{tableNames[i]}\",");
            }

            builder.AppendLine("                _ => string.Empty,");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static List<string> ToUniqueMembers(List<string> tableNames)
        {
            List<string> members = new(tableNames.Count);
            HashSet<string> taken = new(StringComparer.Ordinal) { NONE_MEMBER };

            foreach (string tableName in tableNames)
            {
                string member = ToIdentifier(tableName);

                // 테이블 이름이 달라도 식별자로 깎으면 겹칠 수 있다. "UI Text" 와 "UI_Text" 가 그렇다.
                string unique = member;
                int suffix = 1;
                while (false == taken.Add(unique))
                {
                    unique = $"{member}_{suffix}";
                    ++suffix;
                }

                members.Add(unique);
            }

            return members;
        }

        private static string ToIdentifier(string tableName)
        {
            StringBuilder builder = new(tableName.Length);

            foreach (char c in tableName)
            {
                builder.Append(true == char.IsLetterOrDigit(c) || '_' == c ? c : '_');
            }

            if (0 == builder.Length || (false == char.IsLetter(builder[0]) && '_' != builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }
    }

    internal sealed class LocalTableWatcher : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (false == TouchesTableCollection(importedAssets) &&
                false == HasAssetExtension(deletedAssets) &&
                false == TouchesTableCollection(movedAssets))
            {
                return;
            }

            try
            {
                LocalTableGenerator.TryWrite();
            }
            catch (Exception e)
            {
                // 에셋 임포트 도중이라 던지면 임포트 전체가 말린다. 메뉴로 다시 돌릴 수 있으니 삼킨다.
                Log.Print(Log.LogLevel.Warning, "LocalTable 자동 생성에 실패했다.", exception: e);
            }
        }

        private static bool TouchesTableCollection(string[] paths)
        {
            foreach (string path in paths)
            {
                if (typeof(StringTableCollection) == AssetDatabase.GetMainAssetTypeAtPath(path))
                {
                    return true;
                }
            }

            return false;
        }

        // 지워진 에셋은 타입을 물어볼 대상이 이미 없다. 확장자로만 거른다.
        private static bool HasAssetExtension(string[] paths)
        {
            foreach (string path in paths)
            {
                if (true == path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
