using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using O2un.Core.Utils;
using UnityEditor;
using UnityEditor.Localization;

namespace O2un.Core.Localization.Editor
{
    /// <summary>
    /// String Table Collection 이름에서 테이블 enum 을 뽑는다.
    ///
    /// Roslyn 소스 제너레이터로는 못 만든다 — 테이블은 컴파일에 들어가지 않는 에셋이라
    /// 컴파일러가 볼 수 없다. 그래서 Editor 쪽에서 파일을 직접 쓴다.
    ///
    /// 프레임워크 테이블과 게임 테이블은 각자의 어셈블리로 갈라 쓴다. 한 파일에 모으면
    /// 게임이 테이블을 추가할 때마다 프레임워크 추적 파일이 바뀌어 upstream 싱크마다 충돌한다.
    /// </summary>
    public static class LocalTableGenerator
    {
        private const string NONE_MEMBER = "None";

        private const string FRAMEWORK_OUTPUT_PATH =
            "Assets/0_Framework/00_Script/Core/Localization/Generated/LocalTable.g.cs";
        private const string FRAMEWORK_NAMESPACE = "O2un.Core.Localization";
        private const string FRAMEWORK_ENUM = "LocalTable";

        // 단위 1 결정 2 — 게임이 만드는 모든 것은 이 아래 있다. 테이블 소유자를 이걸로 가른다.
        private const string GAME_ROOT = "Assets/1_Game/";

        private const string GAME_OUTPUT_PATH =
            "Assets/1_Game/00_Script/Localization/Generated/GameLocalTable.g.cs";
        private const string GAME_NAMESPACE = "Game.Localization";
        private const string GAME_ENUM = "GameLocalTable";

        [MenuItem("O2un/Localization/Rebuild LocalTable")]
        public static void Rebuild()
        {
            if (false == TryWrite())
            {
                Log.Print(Log.LogLevel.Info, "LocalTable 은 이미 테이블 목록과 같다.");
            }
        }

        /// <summary>내용이 달라졌을 때만 쓴다. 같은 파일을 다시 쓰면 도메인 리로드만 도는 탓이다.</summary>
        public static bool TryWrite()
        {
            CollectTableNames(out List<string> frameworkTables, out List<string> gameTables);

            bool wrote = WriteIfChanged(
                FRAMEWORK_OUTPUT_PATH,
                Build(FRAMEWORK_NAMESPACE, FRAMEWORK_ENUM, frameworkTables, emitLocKeyBridge: false));

            if (0 == gameTables.Count)
            {
                // 게임 테이블이 사라졌는데 파일이 남으면 없는 테이블을 가리키는 enum 이 컴파일된다.
                if (true == File.Exists(GAME_OUTPUT_PATH))
                {
                    AssetDatabase.DeleteAsset(GAME_OUTPUT_PATH);
                    wrote = true;
                }

                return wrote;
            }

            bool wroteGame = WriteIfChanged(
                GAME_OUTPUT_PATH,
                Build(GAME_NAMESPACE, GAME_ENUM, gameTables, emitLocKeyBridge: true));

            return true == wrote || true == wroteGame;
        }

        private static bool WriteIfChanged(string path, string generated)
        {
            if (true == File.Exists(path) && File.ReadAllText(path) == generated)
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, generated);
            AssetDatabase.ImportAsset(path);

            Log.Print(Log.LogLevel.Info, $"테이블 enum 을 다시 생성했다. ({path})");

            return true;
        }

        private static void CollectTableNames(out List<string> frameworkTables, out List<string> gameTables)
        {
            frameworkTables = new List<string>();
            gameTables = new List<string>();

            foreach (StringTableCollection collection in LocalizationEditorSettings.GetStringTableCollections())
            {
                if (null == collection)
                {
                    continue;
                }

                if (true == string.IsNullOrWhiteSpace(collection.TableCollectionName))
                {
                    continue;
                }

                if (true == IsGameOwned(collection))
                {
                    gameTables.Add(collection.TableCollectionName);
                }
                else
                {
                    frameworkTables.Add(collection.TableCollectionName);
                }
            }

            frameworkTables.Sort(StringComparer.Ordinal);
            gameTables.Sort(StringComparer.Ordinal);
        }

        private static bool IsGameOwned(StringTableCollection collection)
        {
            string path = AssetDatabase.GetAssetPath(collection);

            return false == string.IsNullOrEmpty(path)
                && true == path.StartsWith(GAME_ROOT, StringComparison.OrdinalIgnoreCase);
        }

        private static string Build(string namespaceName, string enumName, List<string> tableNames, bool emitLocKeyBridge)
        {
            StringBuilder builder = new();

            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("//     O2un/Localization/Rebuild LocalTable 메뉴가 String Table Collection 에서 생성한다.");
            builder.AppendLine("//     직접 고치면 다음 생성에서 덮어써진다.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("//------------------------------------------------------------------------------");
            builder.AppendLine();

            if (true == emitLocKeyBridge)
            {
                builder.AppendLine("using O2un.Core.Localization;");
                builder.AppendLine();
            }

            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.AppendLine($"    public enum {enumName}");
            builder.AppendLine("    {");
            builder.AppendLine($"        {NONE_MEMBER} = 0,");

            List<string> members = ToUniqueMembers(tableNames);

            for (int i = 0; i < members.Count; ++i)
            {
                builder.AppendLine($"        {members[i]} = {i + 1},");
            }

            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine($"    public static class {enumName}Extensions");
            builder.AppendLine("    {");
            builder.AppendLine($"        public static string ToTableName(this {enumName} table)");
            builder.AppendLine("        {");
            builder.AppendLine("            return table switch");
            builder.AppendLine("            {");

            for (int i = 0; i < members.Count; ++i)
            {
                builder.AppendLine($"                {enumName}.{members[i]} => \"{tableNames[i]}\",");
            }

            builder.AppendLine("                _ => string.Empty,");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            if (true == emitLocKeyBridge)
            {
                builder.AppendLine();
                builder.AppendLine($"        public static LocKey Key(this {enumName} table, string key)");
                builder.AppendLine("        {");
                builder.AppendLine("            return LocKey.FromTableName(table.ToTableName(), key);");
                builder.AppendLine("        }");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static List<string> ToUniqueMembers(List<string> tableNames)
        {
            List<string> members = new(tableNames.Count);
            HashSet<string> taken = new(StringComparer.Ordinal) { NONE_MEMBER };

            foreach (string tableName in tableNames)
            {
                string member = ToIdentifier(tableName);

                // 테이블 이름이 달라도 식별자로 깎으면 겹칠 수 있다. "UI Text" 와 "UI_Text" 가 그렇다.
                string unique = member;
                int suffix = 1;
                while (false == taken.Add(unique))
                {
                    unique = $"{member}_{suffix}";
                    ++suffix;
                }

                members.Add(unique);
            }

            return members;
        }

        private static string ToIdentifier(string tableName)
        {
            StringBuilder builder = new(tableName.Length);

            foreach (char c in tableName)
            {
                builder.Append(true == char.IsLetterOrDigit(c) || '_' == c ? c : '_');
            }

            if (0 == builder.Length || (false == char.IsLetter(builder[0]) && '_' != builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }
    }

    internal sealed class LocalTableWatcher : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (false == TouchesTableCollection(importedAssets) &&
                false == HasAssetExtension(deletedAssets) &&
                false == TouchesTableCollection(movedAssets))
            {
                return;
            }

            try
            {
                LocalTableGenerator.TryWrite();
            }
            catch (Exception e)
            {
                // 에셋 임포트 도중이라 던지면 임포트 전체가 말린다. 메뉴로 다시 돌릴 수 있으니 삼킨다.
                Log.Print(Log.LogLevel.Warning, "LocalTable 자동 생성에 실패했다.", exception: e);
            }
        }

        private static bool TouchesTableCollection(string[] paths)
        {
            foreach (string path in paths)
            {
                if (typeof(StringTableCollection) == AssetDatabase.GetMainAssetTypeAtPath(path))
                {
                    return true;
                }
            }

            return false;
        }

        // 지워진 에셋은 타입을 물어볼 대상이 이미 없다. 확장자로만 거른다.
        private static bool HasAssetExtension(string[] paths)
        {
            foreach (string path in paths)
            {
                if (true == path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
