using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace CodeGenerator
{
    [Generator]
    public class RequireComponentGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var fieldDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: GeneratorFilterHelper.IsFieldWithAttribute,
                    transform: (ctx, _) => GeneratorFilterHelper.GetFieldWithAttribute(ctx, "RequireComponentField"))
                .Where(m => m != null);

            context.RegisterSourceOutput(fieldDeclarations, (spc, symbol) => Execute(spc, symbol));
        }
        
        private static void Execute(SourceProductionContext context, IFieldSymbol fieldSymbol)
        {
            var namespaceName = fieldSymbol.ContainingNamespace.ToDisplayString();
            var className = fieldSymbol.ContainingType.Name;
            var fieldName = fieldSymbol.Name;
            var fieldType = fieldSymbol.Type.ToDisplayString();

            var propName = fieldName.TrimStart('_');
            propName = char.ToUpper(propName[0]) + propName.Substring(1);

            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("using UnityEngine;");
            sourceBuilder.AppendLine($"namespace {namespaceName}");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine($"    [RequireComponent(typeof({fieldType}))]");
            sourceBuilder.AppendLine($"    public partial class {className}");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine(
                $"        public {fieldType} {propName} => {fieldName} ??= GetComponent<{fieldType}>();");
            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");

            context.AddSource($"{className}_{propName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }
    }
}