using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Text;

namespace CodeGenerator
{
    [Generator]
    public class StaticDataManagerGenerator : IIncrementalGenerator
    {
        private class PropertyInfo { public string Name; public string Type; public PropertyInfo(string n, string t) { Name = n; Type = t; } }
        private class ClassInfo { public string ClassName; public string ManagerName; public string NamespaceName; public List<PropertyInfo> Properties; public ClassInfo(string c, string m, string n, List<PropertyInfo> p) { ClassName = c; ManagerName = m; NamespaceName = n; Properties = p; } }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) =>
                    {
                        if (s is ClassDeclarationSyntax classSyntax)
                        {
                            return classSyntax.AttributeLists.Count > 0;
                        }
                        return false;
                    },
                    transform: (ctx, _) => GetSemanticTarget(ctx))
                .Where(m => m != null);

            context.RegisterSourceOutput(classDeclarations.Collect(), (spc, classes) =>
            {
                var processedClasses = new HashSet<string>();

                foreach (var classInfo in classes)
                {
                    if (processedClasses.Contains(classInfo.ClassName)) continue;
                    processedClasses.Add(classInfo.ClassName);

                    Execute(spc, classInfo);
                }
            });
        }

        private static ClassInfo GetSemanticTarget(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null) return null;
            
            bool hasStaticDataAttribute = false;
            foreach (var attribute in symbol.GetAttributes())
            {
                // 이름이 StaticDataAttribute 이거나 StaticData 인 경우 통과
                if (attribute.AttributeClass?.Name == "StaticDataAttribute" || attribute.AttributeClass?.Name == "StaticData")
                {
                    hasStaticDataAttribute = true;
                    break;
                }
            }
            if (!hasStaticDataAttribute) return null;

            var properties = new List<PropertyInfo>();
            
            var members = symbol.GetMembers().OfType<IPropertySymbol>();
            foreach (var member in members)
            {
                if (member.Name == "Key") continue;
                properties.Add(new PropertyInfo(member.Name, member.Type.ToDisplayString()));
            }

            var namespaceName = symbol.ContainingNamespace?.ToDisplayString() ?? "O2un.Data";
            var className = symbol.Name;
            var managerName = className + "Manager";

            return new ClassInfo(className, managerName, namespaceName, properties);
        }

        private static void Execute(SourceProductionContext context, ClassInfo classInfo)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using O2un.Core;");
            sb.AppendLine();
            sb.AppendLine($"namespace {classInfo.NamespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {classInfo.ManagerName}");
            sb.AppendLine("    {");

            // --- LoadFromExcel 로직 ---
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        protected override void ParseGeneratedData(List<Dictionary<string, string>> rawData)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var tempDict = new Dictionary<UniqueKey, {classInfo.ClassName}>();");
            sb.AppendLine();
            sb.AppendLine("            foreach (var row in rawData)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!row.TryGetValue(\"group\", out var groupStr) || !int.TryParse(groupStr, out int group)) continue;");
            sb.AppendLine("                if (!row.TryGetValue(\"index\", out var indexStr) || !int.TryParse(indexStr, out int index)) continue;");
            sb.AppendLine();
            sb.AppendLine("                var key = new UniqueKey(group, index);");
            sb.AppendLine($"                var data = new {classInfo.ClassName}");
            sb.AppendLine("                {");
            sb.AppendLine("                    Key = key,");

            for (int i = 0; i < classInfo.Properties.Count; i++)
            {
                var prop = classInfo.Properties[i];
                var comma = (i == classInfo.Properties.Count - 1) ? "" : ",";
                string parseLogic = GetParseString(prop.Type, prop.Name);
                sb.AppendLine($"                    {prop.Name} = {parseLogic}{comma}");
            }

            sb.AppendLine("                };");
            sb.AppendLine("                tempDict[key] = data;");
            sb.AppendLine("            }");
            sb.AppendLine("            DataList = tempDict.ToImmutableDictionary();");
            sb.AppendLine("        }");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // --- WriteToBinary 로직 ---
            sb.AppendLine($"        protected override void WriteToBinary(BinaryWriter bw, {classInfo.ClassName} data)");
            sb.AppendLine("        {");
            foreach (var prop in classInfo.Properties)
            {
                sb.AppendLine($"            bw.Write(data.{prop.Name});");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // --- ReadFromBinary 로직 ---
            sb.AppendLine($"        protected override {classInfo.ClassName} ReadFromBinary(BinaryReader br, UniqueKey key)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {classInfo.ClassName}");
            sb.AppendLine("            {");
            sb.AppendLine("                Key = key,");
            
            for (int i = 0; i < classInfo.Properties.Count; i++)
            {
                var prop = classInfo.Properties[i];
                var comma = (i == classInfo.Properties.Count - 1) ? "" : ",";
                string readLogic = GetBinaryReadString(prop.Type);
                sb.AppendLine($"                {prop.Name} = {readLogic}{comma}");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{classInfo.ManagerName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string GetParseString(string type, string name)
        {
            switch (type.ToLowerInvariant())
            {
                case "int": case "system.int32": return $"int.Parse(row[\"{name}\"])";
                case "float": case "system.single": return $"float.Parse(row[\"{name}\"])";
                case "bool": case "system.boolean": return $"bool.Parse(row[\"{name}\"])";
                case "string": case "system.string": return $"row[\"{name}\"]";
                default: return $"row[\"{name}\"]";
            }
        }

        private static string GetBinaryReadString(string type)
        {
            switch (type.ToLowerInvariant())
            {
                case "int": case "system.int32": return "br.ReadInt32()";
                case "float": case "system.single": return "br.ReadSingle()";
                case "bool": case "system.boolean": return "br.ReadBoolean()";
                case "string": case "system.string": return "br.ReadString()";
                default: return "br.ReadString()";
            }
        }
    }
}